Add files via upload
gislaveds-kommun/mediabevararen pull request #1
Opened 2024-11-09 08:28 UTC by HubertusBergman

2024-11-26 09:18 UTC, krahlin requested changes
Hej!
Nu har jag gått igenom och kommenterat en del saker. Om något är otydligt eller du undrar något så kan du bara kommentera eller fråga mig! Har ibland skrivit förslag på kod och namn, se det som förslag och tips för att ändra koden i en riktning, jag kan ha missuppfattat något eller ha fel.

2024-11-26 09:18 UTC, krahlin commented on LICENSE.txt
Det finns redan en likadan license-fil så tänker att den här kan tas bort.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +                    break
Kan man använda generator expression här? Next returnerar första tag-content som hittas då if-satsen är uppfylld och avbryter då itereringen. Om ingen hittas så returneras strängen istället.

```
return_value = next((tag.get_attribute("content") for tag in driver.find_elements(By.TAG_NAME, "meta") if tag.get_attribute("name") and tag.get_attribute("name").lower() == "keywords"), "Inga Keywords specificerade för denna webbsida")
```

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Tänker här att det är bra att fånga specifika exceptions som kan förväntas uppstå, inte bara alla generellt. Tex NoSuchElementException, AttributeError, WebDriverException.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    #driver.quit()
Om den bortkommenterade koden inte ska vara med så ta bort den istället för att ha kvar som kommentar.
Och om den koden inte ska vara med så bör det gå att returnera värdet - `return return_value` - direkt under respektive fall?

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
(Obs att du kanske inte kommer ha flera fall här alls, som vi pratade om och jag skrev i en kommentar längre ner.)

Skriv om till en match case.
Du kan också returnera respektive värde direkt vid varje fall:
```
match option: 
    case 1:
        return driver.title
    case 2:
        return next(.....)
    case 3:
        return .....
    case _:
        return 'Unknown value'
```

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    return domain_with_subdomain
Tänker att du kan ta bort printen (om den inte är viktig, annars kanske vi kan lägga till en log senare?) och istället returnera direkt:

`return urlparse(url).netloc`

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +def create_xml_fgs(row, formatted_date, xml_file_name, tiff_image_name, folder_name, basmetadata_as_lists, driver):
Hade velat att row får ett mer beskrivande namn

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Om jag har tolkat det här rätt så används alla värden i basmetadata_as_lists, förutom det första som är en rubrik? Kommer det alltid vara så eller kan det finnas rader som inte används? Förväntas alla rader ha ett värde eller kan det vara None?
Jag funderar om det går att generalisera if-else samt motsvarande noder nedanför på följande vis:

```
for basmetadata_row in basmetadata_as_lists[1:]:
    if basmetadata_row[1] is not None:
        ET.SubElement(dokument, basmetadata_row[0]).text = str(basmetadata_row[1])
```

De flesta verkar följa det mönstret. Om någon är specialfall så lägg den i en if-sats. Tex ser jag att 'Klassificeringsstruktur' står som 'KlassificeringsstrukturText' när den noden ska sättas. Stämmer det att det ska vara olika? Isåfall lägg till `if basmetadata_row[0] == "Klassificeringsstruktur": ` och skriv det specialfallet.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        elif basmetadata_row[0] == "Serie ":
Är det meningen att det ska vara ett mellanslag i slutet av "Serie "?

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +import requests
Ser inte att requests används i scriptet, isåfall kan du ta bort denna import.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    description  = get_webpage_metadata(url,3,driver) # Get the metadata "Description" from the HTML in the current webpage
Är det nödvändigt att använda 'option' i denna funktion istället för att bara göra alla tre saker direkt i funktionen get_webpage_metadata?

Så kan du här skriva
```
title, keywords, description = get_webpage_metadata(url, driver)
```

Och sen i funktionen högre upp så gör du
```
def get_webpage_metadata(url, driver):
    driver.get(url)
    keywords = next(...det från tidigare kommentar...)
    description = next(.......)

    return driver.title, keywords, description
```

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Samma här som för option 2, men med 'description' istället för 'keywords' samt ändra i defaultsträngen som returneras om inget hittades. Och mer specifika exceptions.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +            return_value = "Inga Keywords specificerade för denna webbsida"
Tänker här att det är bra att fånga specifika exceptions som kan förväntas uppstå istället för alla generellt. Tex NoSuchElementException, AttributeError, WebDriverException.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        elif basmetadata_row[0] == "Arkivbildare":
Om jag har tolkat det här rätt så används alla värden i basmetadata_as_lists, förutom det första som är en rubrik? Kommer det alltid vara så eller kan det finnas rader som inte används? Förväntas alla rader ha ett värde eller kan det vara None?
Jag funderar om det går att generalisera if-else samt motsvarande noder nedanför på följande vis:

```
for basmetadata_row in basmetadata_as_lists[1:]:
    if basmetadata_row[1] is not None:
        ET.SubElement(dokument, basmetadata_row[0]).text = str(basmetadata_row[1])
```

De flesta verkar följa det mönstret. Om någon är specialfall så lägg den i en if-sats. Tex ser jag att 'Klassificeringsstruktur' står som 'KlassificeringsstrukturText' när den noden ska sättas. Stämmer det att det ska vara olika? Isåfall lägg till `if basmetadata_row[0] == "Klassificeringsstruktur": ` och skriv det specialfallet.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Här pratade vi om alternativet att inte ha med 'option' i denna funktion och istället göra alla tre saker direkt i funktionen get_webpage_metadata.

Då kan du här skriva:
```
title, keywords, description = get_webpage_metadata(url, driver)
```

Och sen i funktionen högre upp så gör du
```
def get_webpage_metadata(url, driver):
    driver.get(url)
    keywords = next(...det från tidigare kommentar...)
    description = next(.......)

    return driver.title, keywords, description
```

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    site.text = domain
Kan du skapa och tilldela värdet i ett steg, där det är möjligt. Tex denna blir:
`ET.SubElement(dokument, "Site").text = get_site(url)`

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        # return False
Ska denna inte returnera False om det exceptionet fångas?
Sätt en return False i slutet av funktionen, inte i except-blocken, så kommer den alltid returnera False om den inte har nått fram till return True.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    driver.get("https://www.instagram.com")
Sätt denna och andra strängar som används i funktioner som konstanter högt upp i filen, och sen konstantnamnet här. Tex `driver.get(URL_INSTAGRAM)`.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    driver.implicitly_wait(10)
Denna kan du deklarera innan som `seconds_to_wait_for_page_to_load = 10`

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Du kanske kan ta bort try except här i funktionen och sen göra en try except när du kör funktionen istället, så testar du för hela inloggningen. Är det rimligt?

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Samma som för funktionen ovan tänker jag. 

- Sätt strängar i konstanter och så kan du återanvända "seconds_to_wait..." här, om det ska vara samma tid.

- Eventuellt om try except kan flyttas ut ett steg till där funktionen körs.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    input_field = driver.find_element(By.ID, "username")  # You can also use XPATH or other methods if necessary
Samla elementnamnsträngar som är konstanta i en datastruktur, tex
```
ELEMENT_STRINGS = {
    "username": "username",
    "password": "password",
    "linkedin_login_button": '//button[@aria-label="Logga in"]',
    "linkedin_accept_button": '//span[text()="Acceptera"]'
}
```
Så finns de samlade på ett ställe.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Lägg url och int i konstant

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Samma som för tidigare login-funktioner

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +            button.click()
Du kan sätta strängen i en variabel och sen skriva såhär:

`driver.find_element(By.XPATH, labels['accept_cookies_button']).click()`

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        pass
Om alternativ 2 och 3 inte ska göra något så kan du ta bort dem

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    if type_of_web_extraction == 1:
Använd strängar med beskrivande namn istället för int och sen gör en match case. Tex 1 kan bli 'gislaved_external'.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Förstår inte riktigt varför du gör som du gör här.
Är det meningen att du ska hämta antingen 50 eller 20 tecken beroende på typ av url? Varför just den/de siffrorna?
Måste filnamnet innehålla en del av url'en?

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Tänkte på att eftersom du just nu använder pandas så kan du komma åt ett element direkt istället för att iterera igenom raderna.

När du läser in skriv såhär för att inte få numrerade rader:
`basmetadata = pd.read_excel('basmetadata_extern_webb.xlsx', sheet_name='basmetadata', index_col=0)`

Och sen när du vill ha tex värdet av "Arkivbildare" så skriver du `basmetadata['value']['Arkivbildare']`.

Sen kanske du inte bör använda pandas utan istället använda openpyxl, eftersom det är mindre och enklare, när du inte gör så mycket med datan i sig utan endast läser in och itererar.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        systemnamn_config = ursprung_text  # otherwise it is from variable "Ursprung" if it is from a system like Castor
Kan du inte skriva direkt 
`systemnamn_config = "Webbsidor"` eller `systemnamn_config = ursprung_text`? Beroende på vilken du har som default. Eftersom du vet att den alltid kommer att vara det. Känns som ett mellansteg här?

Alternativt om det finns någon inparameter som heter systemnamn, då kan du skriva
`systemnamn_config = systemnamn if systemnamn.strip() else ursprung_text`

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Jag tycker det blir tydligare om du skriver parenteserna under varandra
```
data = [
    ("Ett", en_variabel),
    (....., .....    ),
    (......., ..... )
    ]
```

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    wb = Workbook()
Byt namn till ett mer beskrivande namn

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    for row in data:
`data` skulle också kunna heta något som beskriver datan på något sätt. Är det `config_data` eller `metadata_for_package_creator`?

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    facebook_password = "your facebook password"
Lösenord (och kanske användarnamn?) bör inte skrivas in direkt i filen. Jag brukar använda en .env fil till känslig information som sen läses in. Och .env filen är med i gitignore så att den inte råkar hamna på git med lösenordsinformation.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    headless = False  # adjust this to true to get full height. False för debugging to see how buttons are clicked
Sätt den till True istället om det är det som är tänkt att man vill ha sen när det körs på riktigt och inte i debugläge.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    pages = pd.read_excel('pages_gislaved_se_extern_webb.xlsx', sheet_name='webpage')
Jag tror du bör använda tex openpyxl istället för pandas.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        os.mkdir("image_temp")  # Create the folder for holding temporary image
Skriv istället
```
if not os.path.isdir(PATH_NAME):
    os.mkdir(PATH_NAME)
```
och deklarera namnet till mappen tidigare, med något bra namn.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        login_to_instagram(driver, instagram_user, instagram_password)  # use only when login to instagram is needed
Här runt login-funktionerna menade jag att du kunde sätta try-except-blocket.

Och fundera på vad du vill ska hända om det misslyckas. Ska körningen avbrytas? Just nu ser det ut som att du fångar exception och sen bara fortsätter.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +            print(f"xml not valid {xml_file_path}")
Är lite förvirrad här också. Varför fortsätter man tills den förra inte längre är valid? Jag tänker mig att man gör allt med en page, validerar och handskas med resultatet.
Något liknande:
```
try:
    do_things_with_page()
    if not validate_xml(...):
        ta bort det som blev fel(?)
```
Eller om allt ska bort om en blir fel?

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +main()
Lägg till en if-name-main och kör mainfunktionen där i.

```
if __name__ == "__main__":
    do_things()
```

2024-11-26 09:18 UTC, krahlin commented on readme.md
> +> A python script to harvest screenshoots from **websites and social media** and prepare them for archiving in the **E-archive LTA**.
screenshots

2024-11-26 09:18 UTC, krahlin commented on readme.md
> +>Takes screenshoots of webpages or social media as **tiff** which is a archiveable image format.
screenshots*
an*

2024-11-26 09:18 UTC, krahlin commented on readme.md
> +>Creates XML with metadata to each screenshoot in **FGS archive XML** format.
screenshot

2024-11-26 09:18 UTC, krahlin commented on readme.md
> +>The **FGS XML structure** is based on **FREDA which is an E-archive cooperation with municipalities in Jönkpings Län**.
Jönköpings

2024-11-26 09:18 UTC, krahlin commented on readme.md
> +>Validates the FGS XML with .XSD file whith the structur of **FREDA FGS XML for Websites**.
with
structure

2024-11-26 09:18 UTC, krahlin commented on readme.md
> +>The button clicks on these types is set for example to the current cookie banner that needs to be clicked. This might change over time when websites are uppdated. That requieres changes in the code
updated

2024-11-26 09:18 UTC, krahlin commented on readme.md
> +>**headless** = True or False : Adjust this to true to get full height. False för debugging to see how buttons are clicked but then full height is not saved in the screenshoot.
for
screenshot

2024-11-26 09:18 UTC, krahlin commented on readme.md
> +>**pages** = pd.read_excel('**pages_gislaved_se_extern_webb.xlsx**', sheet_name='webpage')
Varför finns en rad kod här?

2024-11-26 09:18 UTC, krahlin commented on readme.md
Har kommenterat några stavfel jag hittade.
Det jag hade velat ha tydligare är vad som faktiskt måste finnas med. Tex så skriver du vilken information som finns i basmetadata - är det för att jag behöver skapa en sådan fil med exakt de raderna? Alltså vilka krav behöver jag som användare veta om för att det ska fungera för mig.
Sen kanske någon som arbetar med arkivering tycker det är självklart, men jag blir förvirrad.

2024-11-26 09:18 UTC, krahlin commented on readme.md
Det fanns en README-fil redan, med denna blir det två. Redigera i den befintliga och ta bort denna.

2024-11-26 09:18 UTC, krahlin commented on archiving-of-web-and-social-media.py
Detta är några saker som återkommer som jag tänkt på:
1. Prints som (jag antar) du använt för debug kan du ta bort.
2. Sätt strängar och andra värden i datastrukturer eller konstanter istället för att hårdkoda direkt i funktionsanropen.
3. Try-except blocken känns inte helt logiska just nu, dels att du eventuellt vill att funktioner avbryts om vissa exception sker och dels saknas exceptionhantering för tex loginklicket.
4. Ta bort kommentarer och låt koden förklara sig själv så långt det är möjligt.

2024-11-26 14:48 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +                    break
Ja det borde funka, när jag tittar på den koden och min egen ser jag något som jag inte riktigt fattar med min egen kod
                if name_attr and name_attr.lower() == "keywords":
Antar att det betyder att om name_attr är satt så blir det true och om name_attr.lower() == "keywords" så blir det true oavsätt om det står keywords eller KEYWORDS.  men om name_attr.lower() är keywords eller liknande så är den väl satt så den första satsen för AND känns överflödig. eller vad tycker du? För det kan väl inte betyda att både name_attr och name_attr.lower() ska vara lika med "Keywords" vilket isf också känns som överflödigt.  Vad tror du om detta ;)

2024-11-27 08:04 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +                    break
Ja, delvis! Om vi bara har `name_attr.lower() == "keywords"` så kommer vi få ett AttributeError om name_attr inte skulle finnas, därför behöver vi först kontrollera att den faktiskt finns innan vi anropar på lower(). Om if name_attr är False så kommer den inte att köra resten av if-satsen.

2024-11-27 15:16 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +                    break
Bra, Jag hittade en annan grej med min kod 
Denna kod
if keywords is None
borde vara så här
if keywords is None or keywords =="":
för om man hittar keywords på webbsidan men den är en tomsträng så får man inte texten
Inga Keywords specificerade för denna webbsida

Hur får man in  or keywords =="": 
i din kod för detta?

2024-11-27 15:45 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +                    break
En tom sträng ger False om man gör en if på den. Men du menar om tag.get_attribute("content") == '' , tolkar jag rätt?
Vet vi att den alltid existerar om 'name' finns? För just nu kontrollerar vi inte heller om den finns. Du kan lägga till genom att skriva en till `and` i if-satsen, strip() tar bort alla blanktecken i början och slutet av strängen. Men om vi inte vet att den alltid existerar så behöver vi lägga till en koll för det med, annars ger .strip() ett Error.
```
return_value = next((tag.get_attribute("content") for tag in driver.find_elements(By.TAG_NAME, "meta") if tag.get_attribute("name") and tag.get_attribute("name").lower() == "keywords" and tag.get_attribute("content").strip()), "Inga Keywords specificerade för denna webbsida")
```

2024-11-27 17:13 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +                    break
Exakt för i min kod har jag keywords = tag.get_attribute("content")

Jag tror att den alltid existerar om name finns men jag kan inte vara säker

så då blir det så här 
return_value = next((tag.get_attribute("content") for tag in driver.find_elements(By.TAG_NAME, "meta") if tag.get_attribute("name") and tag.get_attribute("name").lower() == "keywords" and tag.get_attribute("content") and tag.get_attribute("content").strip()), "Inga Keywords specificerade för denna webbsida")

2024-11-28 09:58 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Okay det är nog bra. Tänker du att man ska sätta 
return_value = "Inga Keywords specificerade för denna webbsida"
oavsätt vilket fel det är ändå
eller ska man bara sätta det vid vissa typer av fel?

Vad gör man med felen i  övrigt. Ska man logga dem? eller vad är praxis där?

2024-11-28 09:59 UTC, HubertusBergman commented on LICENSE.txt
Har tagit bort den ena

2024-11-28 10:14 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    #driver.quit()
Koden  #return_value = re.sub('[&]', "_", return_value) finns inte i min kod. Det måste ha blivit något fel på branchen då kanske eller vad tror du?

2024-11-28 12:13 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +                    break
Okej gör så här:

Två stycken hjälpfunktioner högst upp i filen:
```
def tag_has_key_value(tag, key, value=None):
    if value:
        return tag.get_attribute(key) and tag.get_attribute(key).lower().strip() == value
    return tag.get_attribute(key) and tag.get_attribute(key).strip()


def has_keywords_with_content(tag):
    return tag_has_key_value(tag, "name", "keywords") and tag_has_key_value(tag, "content")
```

Sen i funktionen:
```
all_meta_tags = driver.find_elements(By.TAG_NAME, "meta")

generator = (tag.get_attribute("content") for tag in all_meta_tags if has_keywords_with_content(tag))

return next(generator, "Inga Keywords specificerade för denna webbsida")
```
eller `keywords_content = next(.....)` om du inte ska returnera värdet direkt utan kolla upp fler först.
Om jag tolkat rätt så är tanken att gömma undan all krånglig logik som användaren inte behöver förstå.

2024-11-28 12:54 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Egentligen stämmer det väl inte riktigt, nu kommer vi få den strängen som defaultvärde från next() om inte keywords är specificerade. Så om den hamnar i except så måste det vara pga ett faktiskt fel, eller hur?
Hur illa är det om keywords inte finns? Går det fortfarande att arkivera med noteringen att det inte fanns några? Eller behöver just den screenshoten avbrytas? Isåfall kan vi definiera ett eget "inga keywords exception" också.

Vad man gör med felet beror helt på vad för fel och vad man vill ska hända. Det kan tex vara ett fel som gör att man inte kan fortsätta programmet och då får man göra raisea igen för att programmet ska avslutas. Eller om det inte är så kritiskt fel så kan man logga och sen fortsätta. Just nu har vi inte en logg, jag har också print när jag inte har en logger.

2024-11-28 12:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    #driver.quit()
Jag tror att jag skrev kommentaren innan du hade tagit bort det och sen glömde jag ta bort kommentaren efteråt!

2024-11-28 13:08 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +                    break
Hm, jag trodde jag hade kommenterat på den där du hämtar 'description' också, men nu ser jag den inte.

Den kan du iallafall göra på liknande sätt.
```
def has_description_with_content(tag):
    return tag_has_key_value(tag, "name", "description") and tag_has_key_value(tag, "content")
```
Den hade iofs kunnat generaliseras om man skickar in "description" som parameter och använda samma funktion i båda fall, men vänta lite med det för nu så bestämmer vi sen.

Och sen
```
all_meta_tags = driver.find_elements(By.TAG_NAME, "meta")

generator = (tag.get_attribute("content") for tag in all_meta_tags if has_description_with_content(tag))

return next(generator, "Ingen beskrivning specificerad för denna webbsida")
```

Om du tar bort de olika alternativen så behöver du inte definiera `all_meta_tags` en gång till utan använda samma för båda.

2024-11-28 18:13 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Min tanke med try catch är att försöka hitta metadata men om man misslyckas pga något fel eller att det inte finns metadata spelar ingen roll för det är inte kritiskt att det måste finnas metadata av typen keywords i LTA för sökning. Men om det finns så tackar vi inte nej. Så om om det blir ett fel i programmet under den try processen så är det viktigare att fortsätta processen och köra klart så att man inte måste köra om allt från början. Jag tycker därför att felhantering känns som overkill i detta sammanhang.  Dock kan det ju vara bra att logga det om så att man kan om det finns ett mönster i felen som man kanske måste rätta till.

2024-11-28 18:14 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    #driver.quit()
Igen fara ;)

2024-11-28 18:23 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +                    break
Du skriver "Om jag tolkat rätt så är tanken att gömma undan all krånglig logik som användaren inte behöver förstå" Hänger inte riktigt med på vem som är användare i sammanhanget och varför man behöver gömma logik för denne ;) kan du utveckla det lite mer

2024-11-28 18:38 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +                    break
Visst pratade vi om att köra denna typ av funktion här def funktion():

    return a, b
a, b = funktion()

2024-11-29 07:51 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +                    break
Ja det gjorde vi!

Kan vara olika personer men tex en utvecklare som vill använda detta i sin kommun behöver kanske förstå flödet och vad som händer men inte själva detaljerna. Så funktionen ska vara lättläst med bra namn och sen allt det röriga, olika expressions och logiker, finns inkapslat i hjälpfunktioner alternativt i klasser. Det är inte så ofta någon behöver förstå exakt alla detaljer i allt som händer (vet inte om jag håller med obs, jag vill själv oftast förstå allt). Försöker fortfarande förstå mig på det här själv! Tycker det är lite lite luddigt exakt vad som ska vara vart 😄

2024-11-29 07:56 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Ja, loggning kanske är bra då, som du säger. Men vi avbryter inte körningen.
Men om det blev ett fel, då kan det hända att det faktiskt fanns keywords men det blev ett fel, så du kanske ska sätta en annan sträng där? 'Ett fel hände när keywords skulle hämtas'. Eller kan man inte skriva in så i arkivet kanske?
Tycker du kan ha kvar print nu och sen gör vi en logger senare. Men vid varje exceptionhantering så fundera över om det är ett fel som påverkar körningen eller ej, så vi kan hantera det rätt.

2024-11-29 08:18 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Jag tänker att om blev fel fast det fanns keywords så kör vi på ändå och skriver det vanliga meddelandet att det inte fanns keywords. Det är inte superviktigt. Jag tror inte att det ska avbryta på något fel bara logga

2024-11-29 10:45 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +                    break
Hej, jag har fixat till denna kod nu. Jag behåll 2 all_meta_tags = driver.find_elements(By.TAG_NAME, "meta") för att jag vill ha den inom try och jag vill ha två separata try för keywords och description ifall bara en failar så får jag åtminståne något på den andra.

2024-11-29 10:45 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +                    break
här är koden def get_webpage_metadata(url, driver):
    driver.get(url)
    title = driver.title
    try:
        all_meta_tags = driver.find_elements(By.TAG_NAME, "meta")

        generator = (tag.get_attribute("content") for tag in all_meta_tags if has_keywords_with_content(tag))

        keywords = next(generator, "Inga Keywords specificerade för denna webbsida")

    except Exception as e:
        keywords = "Inga Keywords specificerade för denna webbsida"
        print("Keywords meta tag not found or an error occurred:", e)

    try:
        all_meta_tags = driver.find_elements(By.TAG_NAME, "meta")

        generator = (tag.get_attribute("content") for tag in all_meta_tags if has_description_with_content(tag))

        description = next(generator, "Ingen beskrivning specificerad för denna webbsida")

    except Exception as e:
        print("Descripton meta tag not found or an error occurred:", e)
        description = "Ingen beskrivning specificerad för denna webbsida"
    return title, keywords, description

2024-11-29 10:51 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +                    break
Men det är kanske så att den andra behåller värdet från den första en fast den misslyckas så då kan jag nog ta bort den andra

2024-12-02 09:54 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Jag skrev den till detta istället def funktion():

    return a, b
a, b = funktion()

2024-12-02 10:01 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    return domain_with_subdomain
Jag gjorde så här och döpte även om funktionsnamnet så att det säger mer
def get_domain_from_url(url):  
    return urlparse(url).netloc

2024-12-02 10:04 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    return domain_with_subdomain
Det låter bra!
Vill bara tillägga att du inte behöver skriva i kommentar vad du ändrar i koden, det räcker med att du ändrar och sen gör commit och push till cleanup, då kommer förändringarna synas här i denna pr.

2024-12-02 10:17 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +                    break
Jag tror den behåller om det inte var just den raden som blev fel. Du skulle kunna lägga till `all_meta_tags = None` innan båda try-catch och sen `if all_meta_tags is None: ` innan du gör all_meta_tags den andra gången, då kommer den bara göra det andra gången om den inte redan har ett värde. 

Nu är jag jättepetig men kan du byta plats så att koden i båda except står i samma ordning, nu är print först i den andra men inte i den första. 😄 
Och du kan välja hur du vill ha returnvärdet om det blir ett exception, men vill helst att du tar bort från printen så det inte står att keywords/description inte är specificerade, eftersom jag tänker att vi inte vet det, vi vet bara att det blev något fel när keywords eller description skulle hämtas. Så typ "Error occurred trying to get description data: {e}" Eller något.

2024-12-02 10:36 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Det blir bra! (Antar nu att du bara använt 'a' och 'b' som exempelnamn här i kommentaren, inte i själva koden)

2024-12-03 13:57 UTC, HubertusBergman commented on readme.md
> +>**headless** = True or False : Adjust this to true to get full height. False för debugging to see how buttons are clicked but then full height is not saved in the screenshoot.
Hänger inte med på vad du menar ;)

2024-12-03 13:59 UTC, HubertusBergman commented on readme.md
> +>**pages** = pd.read_excel('**pages_gislaved_se_extern_webb.xlsx**', sheet_name='webpage')
Förmodlingen copy paste som blev fel, måste gå igen hela readme efter att vi gör om till terminal-program ändå ;)

2024-12-03 14:01 UTC, HubertusBergman commented on readme.md
Det är som du säger att det måste finnas en fil med exakt de raderna. Kanske inte alla som jobbar med Arkiv förstår det för det finns många olika sätt att jobba med arkiv. Men tror nog att ganska många skulle förstå det.

2024-12-03 14:01 UTC, HubertusBergman commented on readme.md
Yes

2024-12-03 14:07 UTC, krahlin commented on readme.md
> +>**headless** = True or False : Adjust this to true to get full height. False för debugging to see how buttons are clicked but then full height is not saved in the screenshoot.
Menar bara stavningningen. I meningen "False för debugging to see how buttons are clicked but then full height is not saved in the screenshoot." så har du skrivit "för" istället för "for" och "screenshoot" istället för "screenshot".

2024-12-03 17:42 UTC, HubertusBergman commented on readme.md
> +>**headless** = True or False : Adjust this to true to get full height. False för debugging to see how buttons are clicked but then full height is not saved in the screenshoot.
Aha ;)

2024-12-03 17:47 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Exakt ;)

2024-12-03 17:49 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +def create_xml_fgs(row, formatted_date, xml_file_name, tiff_image_name, folder_name, basmetadata_as_lists, driver):
fixat

2024-12-03 17:50 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Har gjort en push på ett förslag på detta

2024-12-03 17:52 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +        elif basmetadata_row[0] == "Serie ":
Nej, men detta försvann nu när jag fixade create_xml_fgs

2024-12-03 17:54 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +import requests
hittar inte den, måste ha tagit bort den redan

2024-12-03 17:54 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    description  = get_webpage_metadata(url,3,driver) # Get the metadata "Description" from the HTML in the current webpage
fixat

2024-12-03 17:56 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Vi gör en logg istället

2024-12-03 17:56 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +            return_value = "Inga Keywords specificerade för denna webbsida"
Vi loggar istället, visst sa vi det

2024-12-03 17:59 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +        elif basmetadata_row[0] == "Arkivbildare":
Här verkar vara en dubblett av kommentaren, tycks ha svarat på denna längre upp

2024-12-03 17:59 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
fixat

2024-12-03 18:12 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    site.text = domain
fixat

2024-12-03 18:13 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +        # return False
fixat

2024-12-03 18:17 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Kanske men det jag främst vill veta är om button gick att klicka på för det är det som kan gå fel då det är en adress i trädet i html för webbsidan som lätt kan ha ändrats

2024-12-04 09:14 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +        pass
fixat

2024-12-05 05:38 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Det finns säkert många sätt att skapa ett filnamn. Men jag brukar alltid sätta samman saker som har med filen att göra så att det är lättare att se vad filen är på namnet. När det är en personakt så brukar jag lägga in namnet på personen plus andra saker som gör att filnamnet blir unikt. t ex personummer.  När jag skapar detta filnamn på en utskrift av en webbsida känns det naturligt att använda url:en för den säger lite om vad filen innehåller. Problemet i detta fall är att url:en ofta är ganska lång så därför kapar jag den vid 50 tecken och sätter till en tidpunkt som gör namnet unikt ifall den första delen på url:en är samma på flera filnamn.  Jag tror att detta med 20 tecken ska vara att om strängen är mindre än 50 tecken lång så tar jag 20 tecken istället. Jag minns inte om det var så men det låter rimligt nu i efterhand. 50 tecken ger oftast ett unikt namn direkt utan tidpunkt. 20 tecken ger ett unikt namn på mindre url:er. Men som säkerhet har jag ändå tidpunkten ifall det blir samma som ett annat filnamn. Men det ser ut som koden kollar om det är en sträng och om det inte är det sätter det till en 20 char lång sträng. Om det inte är så att den kollar att det är inte är en 50 char lång sträng.

2024-12-05 05:40 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Detta blev väl fixat när create_xml_fgs blev ändrad

2024-12-05 05:58 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +        systemnamn_config = ursprung_text  # otherwise it is from variable "Ursprung" if it is from a system like Castor
Jag fixade detta som det andra förslaget du hade och satte systemnamn i config-sektionen istället med en  inparameter till create_package_creator_config

2024-12-06 09:45 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Har ändrat till match case på detta

2024-12-06 09:50 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Detta är fixat nu

2024-12-06 09:56 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
Jag tror jag hänger med på vad du menar med basmetadata['value']['Arkivbildare'] och då att man kan sätta XML-klassen direkt utan att loopa igenom och kolla vilken som kommer på tur i listan

2024-12-06 09:56 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
fixat

2024-12-06 10:09 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    wb = Workbook()
fixat

2024-12-06 10:10 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    for row in data:
fixat

2024-12-06 11:03 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    facebook_password = "your facebook password"
fixat en .env

2024-12-06 11:33 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +        os.mkdir("image_temp")  # Create the folder for holding temporary image
fixat

2024-12-06 11:38 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +        login_to_instagram(driver, instagram_user, instagram_password)  # use only when login to instagram is needed
Det var här vi pratat om att jag kör try för man kan vara inloggad redan och då måste man köra try för annars kraschar det. Jag vill också specifikt veta vilken knapp som misslyckades. vi får logga det på något sätt

2024-12-06 11:39 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +            print(f"xml not valid {xml_file_path}")
Om en blir fel ska man avbryta för då är paket inte fullständigt. Då finns det en tiff som saknar xml

2024-12-06 11:48 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +            print(f"xml not valid {xml_file_path}")
Man kan ju ta bort tiffen så klart men det är ju bättre att försöka fixa felet i xml:en för med största sannolikhet kommer resten av  xml:erna också att bli fel så det är ingen idé att fortsätta

2024-12-06 11:48 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +main()
Har fixat

2024-12-06 11:50 UTC, HubertusBergman commented on readme.md
> +> A python script to harvest screenshoots from **websites and social media** and prepare them for archiving in the **E-archive LTA**.
fixat

2024-12-06 11:51 UTC, HubertusBergman commented on readme.md
> +>Takes screenshoots of webpages or social media as **tiff** which is a archiveable image format.
fixat

2024-12-06 11:52 UTC, HubertusBergman commented on readme.md
> +>Creates XML with metadata to each screenshoot in **FGS archive XML** format.
fixat

2024-12-06 11:52 UTC, HubertusBergman commented on readme.md
> +>The **FGS XML structure** is based on **FREDA which is an E-archive cooperation with municipalities in Jönkpings Län**.
fixat

2024-12-06 11:53 UTC, HubertusBergman commented on readme.md
> +>Validates the FGS XML with .XSD file whith the structur of **FREDA FGS XML for Websites**.
fixat

2024-12-06 11:57 UTC, HubertusBergman commented on readme.md
> +>The button clicks on these types is set for example to the current cookie banner that needs to be clicked. This might change over time when websites are uppdated. That requieres changes in the code
fixat

2024-12-06 11:59 UTC, HubertusBergman commented on readme.md
> +>**pages** = pd.read_excel('**pages_gislaved_se_extern_webb.xlsx**', sheet_name='webpage')
har tagit bort detta nu

2024-12-09 11:53 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    driver.get("https://www.instagram.com")
fixat

2024-12-09 11:54 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    driver.implicitly_wait(10)
fixat

2024-12-09 11:55 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
fixat

2024-12-09 11:55 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +            button.click()
fixat

2024-12-09 11:55 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +    if type_of_web_extraction == 1:
fixat

2024-12-09 11:56 UTC, HubertusBergman commented on archiving-of-web-and-social-media.py
> +
fixat

2024-12-09 15:07 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Vi kollar igenom alla exceptions senare tänker jag

2024-12-09 15:10 UTC, krahlin commented on readme.md
Det är tydligast att du skriver ut det. Det skadar inte att vara lite för tydlig, jag tänker att den som ska arbeta med koden kanske inte kan så mycket om arkivering.

2024-12-09 15:17 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +FACEBBOK_COOKIE_BANNER = "//span[text()='Tillåt alla cookies']"
Det kanske vore bra att lägga dessa i en separat fil eftersom de är så många. Importera filen som `'import constants as C'` så kan du skriva `'C.KONSTANTEN'` med passande namn.

2024-12-09 16:40 UTC, krahlin requested changes
Superbra jobbat!
Hade några kommentarer du kan fixa till. Sen var det någon bit som var luddig som jag inte kommenterade men jag tror att mycket av det kommer att ordna sig när vi lägger till och ändrar till ett command line program.

2024-12-09 16:40 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    return unique_filename_date_time
Flytta de här hjälpfunktionerna till högst upp i filen där de andra hjälpfunktionerna är.

2024-12-09 16:40 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +                   ("Schema", schema), ("Contract", contract)]
Sista raden här blev två styck

2024-12-09 16:40 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +
Tolkar jag rätt att du här modifierar namnen på alla basmetadata samt kolumnrubrikerna?
Detta kanske ska vara i en hjälpfunktion, vars funktion är att rensa eller 'preprocess' rubriker och namn.

2024-12-09 16:40 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +            xml_file_name = name_splitted[0] + ".xml"
Bör du använda hjälpfunktionen som splittar strängar till denna split?

2024-12-09 16:40 UTC, krahlin commented on readme.md
> +>
Detta kommer nog att behöva ändras sen, eller hur? När det är ett cli program får vi skriva in hur man kör programmet i terminalen och vilka flaggor, parametrar man kan/ska skicka med. Jag undrar om du ska ta bort en del av texten redan nu?

2024-12-09 16:40 UTC, krahlin commented on readme.md
> +
Samma med hela denna del, att det troligen kommer behöva modifieras något, men jag tänker att vi fixar det efter att vi vet mer exakt hur programmet kommer se ut och användas.

2024-12-11 12:56 UTC, krahlin approved these changes
Bra jobbat!

2024-12-11 12:56 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    return basmetadata
Tanke: om du istället döper till funktionen och parametern till 'prepare_and_clean_columns_and_index(data)' så blir den mer generell. Men det känns inte jätteviktigt just nu eftersom det väl inte finns annan data som också gör detta?

2025-01-08 14:57 UTC, krahlin requested changes
Så, nu har jag gått igenom allt och skrivit lite fler kommentarer! 🙂

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +# from selenium.webdriver.chrome.options import Options
Ta bort

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    process_strukturerat = ET.SubElement(dokument, "ProcessStrukturerat")
Våra variabler har oftast ett namn på engelska, men i denna funktion finns några på svenska - den här, dokument och webbsida. Ska vi ändra namnet på dessa?

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    ET.SubElement(dokument, "Webbadress").text = url
Lägg en tom rad mellan denna och nästa rad 'title, keywords.....  '

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        file.write(formatted_xml)
Funderar på om detta (eller en delmängd av det) ska läggas i en separat funktion med bra namn på vad som händer?

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +def validate_xml(xml_file, xsd_file):
xsd_file behöver inte skickas med, den finns tillgänglig genom `conf.`

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    driver.maximize_window()
Denna rad görs när driver skapas, behöver den köras här också?

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    driver.implicitly_wait(const.TIMEOUT_SECONDS)
Finns det tillfällen då load_webpage körs och vi inte vill ha en wait? Om inte, skulle denna wait kunna läggas in i load_webpage-funktionen? Så finns alltid wait när man laddar en sida.

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +def capture_full_page_screenshot_with_custom_width(output_path, width_of_screenshot, type_of_web_extraction, url):
width_of_screenshot behövs inte som parameter

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    WebdriverClass.load_webpage(url)
Här finns inte implicitly_wait efter load_webpage, bör det finnas med eller behövs det inte just här?
Är det pga den andra wait som kommer efter, varför den wait istället isåfall?

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    print(f"Saved screenshot to {output_path}")
Detta skulle kunna vara i en klassfunktion i WebdriverClass, typ `def take_screenshot(cls, output_path):`

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +                wait.until(EC.element_to_be_clickable((By.XPATH, const.GISLAVED_SE_COOKIE_BUTTON))).click()
Wait-biten görs på olika sätt här, i de flesta andra fall är det så som i case 'gislaved.se'. Att den delas upp. Skulle det kunna skrivas mer som i den övre, med radbryt och färre uppdelningar?

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +def create_tiff_screenshot(url, folder_name, width_of_screenshot, type_of_web_extraction):
Samma här med width_of_screenshot

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    login_button.click()
Lägg en try-except runt login-knapptrycket

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    driver.find_element(By.XPATH, const.INSTAGRAM_LOGIN_BUTTON).click()
Lägg en try-except runt login.
I except raisea nytt exception efter meddelandet skrivits ut så att funktionen avbryts och inte fortsätter.

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    print(io['extraction completed'])
Runt detta blir det då som du får ha en till try-except för att fånga re-raiseade exception vid eventuell fail av inlogg. Jag tycker att vi skapar ett eget Exception som heter typ `LoginException` eller liknande, och sen raisear det exceptionet i except-blocket runt login-trycken. Sen fångas det exceptionet här. Då kommer programmet fånga och fortsätta att köra om vårt loginexception sker men inte om något annat oväntat skulle hända. Gör en fil exception.py med exceptionet och importera det till denna fil

```
class LoginException(Exception):
    pass
```

Och flytta `WebdriverClass.quit_driver()` hit istället, så att det alltid körs efter run_web_extraction oavsett om det blir ett exception eller inte. Nu om funktionen avbryts av ett exception så kommer den aldrig att köra quit_driver och om programmet inte stängs ner utan fortsätter så kan det då bli fel.

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    WebdriverClass.quit_driver()
Flytta denna rad till efter vart denna funktion anropats. (Gjorde en kommentar där också)

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +            print(xml_file_name)
Antingen ta bort denna print eller lägg till så den skriver ut lite mer information istället för bara ett namn

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +def create_package_creator_config(basmetadata, folder_name, schema, contract, systemnamn):
schema, contract och systemnamn finns tillgängliga genom conf

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +    empty_systemnamn = io['empty_systemnamn']
Den här deklarationen behövs nog inte, väl? Tänker att `io['empty_systemnamn']` kan skrivas direkt där det används, att det är ungefär lika tydligt.

2025-01-08 14:57 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +            conf.systemnamn = input(io['question_systemnamn'])
Här kanske det borde läggas till en print med vilket systemnamn som det ändrades till?

2025-01-08 14:57 UTC, krahlin commented on basmetadata_extern_webb.xlsx
Den här filen verkar inte användas och kanske bör tas bort?

2025-01-08 14:57 UTC, krahlin commented on constants.py
> +    'exit_ctrlc': "Exited the program with ctrl+c",
Jag tycker att denna kan ändras till att endast informera om att användaren har tryckt på ctrl+c. För att 'exited_program' kommer skrivas efteråt.

2025-01-08 14:57 UTC, krahlin commented on pages_gislaved_se_extern_webb.xlsx
Samma här, att denna kan tas bort?

2025-01-08 14:57 UTC, krahlin commented on readme.md
> +>Run the python script in **Spyder**
Ändra denna del så att den beskriver hur man kan använda programmet som det ser ut idag. Typ att man får gå in i en terminal, navigera till där filen finns och sen vad man behöver skriva för att starta det, `python archiving_of_web...`.

Kanske också ha med ett stycke om att programmet fungerar så att användaren kan välja vissa filer och konfigurationer i programmet för att sedan köra biten som fixar med själva screenshoten och xml'en.

2025-01-08 14:57 UTC, krahlin commented on readme.md
> +# Configuration
Ändra denna delen så den innehåller
- vilka settings som finns och vad de betyder/innebär (förslagsvis under en egen underrubrik?)
- att några av settings finns som default och vilken fil man kan kolla i för att se dem (skriv inte ut alla default-värden här)
- att en fil vid namn .env ska finnas och exakt vad som behöver stå där i samt vart man ska placera filen
- de excelfiler man kan ha som behöver se ut på ett specifikt sätt, skriv ner dessa i detalj, ungefär som i handlingsplanen. Så det är tydligt vad som är ett krav och inte.

Skriv också här eller om det passar bättre under en annan rubrik(?) vilka sidor som går att crawla med programmet. Alltså vilka web extraction types som finns att välja på. Det kanske faller under första punkten iofs?..

2025-01-08 14:57 UTC, krahlin commented on readme.md
> +>The button clicks on these types is set for example to the current cookie banner that needs to be clicked. This might change over time when websites are updated. That requieres changes in the code n
Jag tycker inte att vi här ska blanda in vad andra kan ändra i själva koden, utan håll det till att skriva om vad detta program faktiskt gör. Tycker det är rimligt att förvänta sig att användaren förstår att man behöver göra ändringar ifall man vill använda programmet till andra sidor eller liknande som programmet inte är skapat för.

2025-01-08 14:57 UTC, krahlin commented on webdriver_class.py
> +        options.add_argument(f"--window-size={const.WIDTH_Of_SCREENSHOT},1080")
Är 1080 höjden? Tycker vi ska ha den som en konstant också, för tydlighet.

2025-01-08 14:57 UTC, krahlin commented on webdriver_class.py
> +        cls._driver.get(url)
Vi kanske borde lägga till en koll här att cls._driver inte är None.
Vet inte vad som är bästa sättet men vi skulle kunna göra `cls.get_driver()` istället för att direkt använda _driver. Eftersom den funktionen handskas med fallet att den är None. Och då blir det den som funktioner alltid går igenom ifall de behöver använda _driver till något, och vill att den ska existera. (Inte i `quit_driver` alltså, för där vill vi att den ska sluta existera.)

2025-01-09 11:35 UTC, krahlin requested changes
Var några mindre saker jag kommenterade på men annars ser ändringarna bra ut!

2025-01-09 11:35 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        print(f"Login failed: {e}")
Lägg till en `finally: ` och flytta quit_driver dit, som det är nu så kommer quit driver inte att köras om ett fel uppstår i run_web_extraction

2025-01-09 11:35 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        print(f"Error on instagram login {e}")
Här i except, efter print, ska `raise LoginException` stå. Och på samma ställe i login för facebook och linkedin.

2025-01-09 11:35 UTC, krahlin commented on archiving-of-web-and-social-media.py
>          print(f"Error: {e}")
`raise LoginException`

2025-01-09 11:35 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +        print(f"Error on linkedin login {e}")
`raise LoginException`

2025-01-09 11:35 UTC, krahlin commented on archiving-of-web-and-social-media.py
> +            print(f"converted to tif: {tiff_image_name}")
Här ska det stå 'tiff' med två f, eller?
Och stort C pga början av mening tänker jag.

2025-01-10 14:24 UTC, krahlin requested changes
Hej!
Har gått igenom det mesta och skrivit lite kommentarer.

2025-01-10 14:24 UTC, krahlin commented on archiving-of-web-and-social-media.py
>          name_field.send_keys(Keys.RETURN)
Jag undrar om inte dessa funktioner ska ligga i webdriverklassen? Vad tror du?

2025-01-10 14:24 UTC, krahlin commented on archiving-of-web-and-social-media.py
>  def get_webpage_metadata(url):
Samma med denna, om den ska vara i Webdriverklassen?

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>Create a .evn file with this content below, and put it in the main folder of the program.
Jag tycker det är tydligare om du skriver "Create a file and name it '.env' ". (Och det har blivit stavfel här, det står '.evn' nu).

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +is needed for users and passwords for social media accounts
Denna mening är inte helt korrekt:
- 'works' ska vara 'work'
- är det rätt att 'script' står där det står? Känns som att det är felplacerat eller glömt tagits bort när jag hör meningen i mitt huvud
- 'usernames' istället för bara 'users'
- Det saknas en punkt i slutet av meningen

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +structure as the sample files. The structur is explain further down.
Två stavfel:
- 'structure'
- 'explained'

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +## The three settings files will be explaind here: ###
'explained' här med

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>These are default settings that can be change in the menu while the program is running.
Stavfel här, ska stå 'can be changed'

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>These are settings that i are used in the program but they can not be changed when the program is running
Ta bort fristående 'i' innan 'are', och punkt i slutet

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>FACEBOOK_COOKIE_BANNER = "//span[text()='Tillåt alla cookies']"
Här blir det tydligare tycker jag om det står tex
'The current Facebook cookie banner makes the constant look like this

    FACEBOOK_COOKIE_BANNER = "....texten..."

if the banner is changed, the constant might also need to be modified accordingly.'

Eller något åt det hållet.

Plus såg stavfel - ska stå 'Example' i rubriken, och 'Facebook' saknar sitt 'e'

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +## The struture of the input data excel files is exlained here ###
Ska stå 'structure' och 'explained'

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>The following are the two columns of the pages excel. The columns need to be exaktly like this.
'exactly' med c

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>The second is a short description of the url that goes in the FGS node webbsida.
Här tycker jag det blir tydligare att skriva mer uppstaplat, typ

The excel file 'pages' needs to have the following information:
> The first column named **Webbadress** containing the url to be crawled

> The second column named **Webbsida** containing a short description of ......

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>default_sample_metadata.xlsx
Samma här som i pages, att lägga till att detta är namnet på filen

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>Further down is a list of the rows in the first column of the excel with basmetadata.
Nu blandas 'basemetadata' och 'basmetadata' i texten. Vet inte vilken man bör ha, men skulle vilja att det inte är båda, förutom om det är filnamn eller så.

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>
Jag tycker att det blir rörigt och otydligt här när det hoppas mellan att nämna kolumn ett och två efter varandra.

Tänker om det kan skrivas tydligare, ett alternativ skulle kunna vara att lägga till en kort sammanfattning i början, något som:
'The excel file contains two columns - the first one is for the names and the second is for the values.'

Och att skriva allt som har med kolumn 1 klart och sen skriva allt om kolumn 2.

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>You can change the defult xsd file while the program is running but then the metadata excel indata has to match the new xsd.
Stavfel: 'default'

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>***Default sample metadata colums***
Ska det inte vara rows här? Att det är en per rad, kolumnerna skrev vi ovanför att det bara var två styck.

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +
Tycker att det skulle kunna vara en punktlista med dessa? Alltså '-' framför orden

2025-01-10 14:24 UTC, krahlin commented on readme.md
Bra skrivet!
En sak jag tänker på är formateringen (heter det så?), att det ofta är '>' i början av raderna, men inte överallt. Är det medvetet du har gjort så?
Annars tycker jag det kan tas bort när det bara är vanlig text, och sen gör indragningar som går att kopiera när det till exempel är text som ska skrivas i terminalen.

2025-01-10 14:24 UTC, krahlin commented on readme.md
> +>python -m pip pip install python-dotenv
Dessa kan vara i en sådan liten ruta med kopieraknapp.
Tror det är blankrad innan och efter meningen och börja raden med fyra blanksteg, för att få en sådan ruta.

2025-01-13 09:47 UTC, krahlin requested changes
Jättebra! Bara lite småsaker som jag kommenterat!

2025-01-13 09:47 UTC, krahlin commented on archiving-of-web-and-social-media.py
Eftersom det nu endast är konstanten 'PATH_TO_IMAGE_TEMP' som används i denna fil, från konstanterna, så tycker jag att du bara importerar den istället för alla. `from constants import PATH_TO_IMAGE_TEMP` och ta bort `import constants`.

2025-01-13 09:47 UTC, krahlin commented on readme.md
> +FACEBOOK_COOKIE_BANNER = "//span[text()='Tillåt alla cookies']"
Denna rad med konstanten vore bra om den hade annan formatering, antingen bara en '>' eller om den ska stå som kod?

2025-01-13 09:47 UTC, krahlin commented on readme.md
> +>-Kommentar
Om du tar bort '>' så tror jag att bindestrecken kommer att bli till punkter istället

2025-01-13 09:47 UTC, krahlin commented on readme.md
> +The first column named **Webbadress** containing the url to be crawled
Saknas punkt i slutet av meningen

2025-01-13 09:47 UTC, krahlin commented on readme.md
> +The second column named **Webbsida** containing a short description of the url and the program puts it into the FGS node webbsida.
Tycker det var lite otydligt efter 'url', min första tanke när jag läste var att 'and program' var en fortsättning på vad man skulle skriva in i kolumnen. Kanske sätt en punkt efter url och gör till två meningar. '...of the url. The program...'?

2025-01-13 09:47 UTC, krahlin commented on readme.md
> +The values in the second column need to match the validation criteria in the default xsd file
Saknas en punkt

2025-01-13 09:47 UTC, krahlin commented on webdriver_class.py
> +        name_field = cls.get_driver().find_element(By.NAME, name)
Här skulle vi kunna använda funktionen `cls.find_element_by_name`

2025-01-13 09:47 UTC, krahlin commented on webdriver_class.py
> +        name_field = cls.get_driver().find_element(By.ID, name)
Och här `cls.find_element_by_id`

2025-01-13 09:47 UTC, krahlin commented on webdriver_class.py
> +        cls._driver.save_screenshot(output_path)
Borde denna ropa på `get_driver` istället för att använda `_driver`?

2025-01-13 09:47 UTC, krahlin commented on webdriver_class.py
> +        cls._driver.implicitly_wait(const.TIMEOUT_SECONDS)
Det känns som att timeout-konstanten kanske hör bättre hemma som en klassvariabel i denna klass? Vad tror du?

2025-01-13 10:59 UTC, krahlin reviewed
Toppen!

2025-01-13 11:08 UTC, closed without merging